name: waves_spy
description: Waves Address Explorer (Experimental)

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.0.0
  provider: ^6.0.2
  flutter_datetime_picker: ^1.5.1
#  date_time_picker: ^2.1.0
  date_time_picker:
    git:
      url: https://github.com/DavidHDJ/date_time_picker.git
      ref: 2.1.1
  url_launcher: ^6.1.2
  dropdown_search: ^5.0.6
  firebase_analytics: ^10.4.1
  firebase_core: ^2.13.0
  get_it: ^7.2.0
  fl_chart: ^0.62.0
  fast_base58: ^0.2.1
  fluttertoast: ^8.0.9
  flutter_html_v3: ^3.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/static/RobotoMono-Regular.ttf

  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/logo.png
