name: waves_spy
description: Waves Address Explorer (Experimental)

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.2
  flutter_datetime_picker: ^1.5.1
  date_time_picker: ^2.1.0
  url_launcher: ^6.1.2
  dropdown_search: ^4.0.1
  firebase_analytics: ^9.1.9
  firebase_core: ^1.17.1
  get_it: ^7.2.0
  fl_chart: ^0.51.0
  fast_base58: ^0.2.1
  fluttertoast: ^8.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/logo.png
